
server_ip: 192.168.10.50

hosts:
    server:
        addr: clnode197.clemson.cloudlab.us
        ip: {0.server_ip}

    client0:
        addr: clnode209.clemson.cloudlab.us
        ip: 192.168.10.10

    client1:
        addr: clnode213.clemson.cloudlab.us
        ip: 192.168.10.11

    client2:
        addr: clnode185.clemson.cloudlab.us
        ip: 192.168.10.12

    client3:
        addr: clnode203.clemson.cloudlab.us
        ip: 192.168.10.13

    client4:
        addr: clnode194.clemson.cloudlab.us
        ip: 192.168.10.14

    client5:
        addr: clnode205.clemson.cloudlab.us
        ip: 192.168.10.15
