
server_ip: 192.168.10.50

hosts:
    server:
        addr: clnode197.clemson.cloudlab.us
        ip: {0.server_ip}

    client0:
        addr: clnode209.clemson.cloudlab.us
        ip: 192.168.10.10 # used as src ip in client program
        rand: 401572 # prevents customers from having the same seed

    client1:
        addr: clnode213.clemson.cloudlab.us
        ip: 192.168.10.11
        rand: 585508

    client2:
        addr: clnode185.clemson.cloudlab.us
        ip: 192.168.10.12
        rand: 135491

    client3:
        addr: clnode203.clemson.cloudlab.us
        ip: 192.168.10.13
        rand: 799764

    client4:
        addr: clnode194.clemson.cloudlab.us
        ip: 192.168.10.14
        rand: 513682

    client5:
        addr: clnode205.clemson.cloudlab.us
        ip: 192.168.10.15
        rand: 949674
