
server_ip: 192.168.10.50

hosts:
    server:
        addr: clnode197.clemson.cloudlab.us
        ip: {0.server_ip}

    client0:
        addr: clnode196.clemson.cloudlab.us
        ip: 192.168.10.10 # used as src ip in client program
        rand: 401572 # prevents clients of has the same seed

    client1:
        addr: clnode182.clemson.cloudlab.us
        ip: 192.168.10.11
        rand: 585508

    client2:
        addr: clnode191.clemson.cloudlab.us
        ip: 192.168.10.12
        rand: 135491

    client3:
        addr: clnode181.clemson.cloudlab.us
        ip: 192.168.10.13
        rand: 799764

    client4:
        addr: clnode188.clemson.cloudlab.us
        ip: 192.168.10.14
        rand: 513682

   # client5:
   #     addr: clnode215.clemson.cloudlab.us
   #     ip: 192.168.10.15
   #     rand: 949674
