
server_ip: 192.168.10.200

hosts:
    server:
        addr: clnode237.clemson.cloudlab.us
        ip: {0.server_ip}

    client0:
        addr: 127.0.0.1

    client1:
        addr: clnode250.clemson.cloudlab.us
        ip: 192.168.10.1
